exclude: '^docs/conf.py'

repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: check-toml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=no']
  - id: flake8
    args: ['--max-line-length=88']  # default of Black
    additional_dependencies:
    - flake8-bugbear
    - flake8-comprehensions
    - flake8-debugger
    # - flake8-eradicate
    #- flake8-executable
    - flake8-mock
    - flake8-mutable
    # - pandas-vet  # not worthy if you are not using pandas (e.g. PD011)

- repo: https://github.com/PyCQA/bandit
  rev: 1.6.2
  hooks:
  - id: bandit
    args: [--exclude, tests/]

- repo: https://github.com/humitos/mirrors-autoflake.git
  rev: v1.1
  hooks:
  - id: autoflake
    args: [
      --in-place,
      --remove-all-unused-imports,
      --remove-unused-variables,
    ]

- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
    language_version: python3.6

- repo: https://github.com/asottile/blacken-docs
  rev: v1.4.0
  hooks:
  - id: blacken-docs

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  - id: isort


